steps:
    - name: node
      entrypoint: npm
      args: ['install']
    - name: 'gcr.io/cloud-builders/gcloud'
      args: [ 'compute', 'ssh', 'heyhatch@movieroulette-1', '--command=rm -rf /home/heyhatch/backend/*', '--zone=us-central1-a', '--project=igneous-future-259601']
    - name: 'gcr.io/cloud-builders/gcloud'
      args: [ 'compute', 'scp', '--recurse', '--zone=us-central1-a', '--project=igneous-future-259601', '/workspace', 'heyhatch@movieroulette-1:/home/heyhatch/backend']