steps:
    - name: 'gcr.io/cloud-builders/gcloud'
      args: [ 'compute', 'scp', '--recurse', '--zone="us-central1-a"', '--project="igneous-future-259601"', '.', 'heyhatch@movieroulette-1:/home/heyhatch/backend']